merge_method: ties
base_model: models/backbones/base
dtype: float32

parameters:
  normalize: true
  int8_mask: false
  rescale: true  

slices:
  - sources:
      - model: models/backbones/base
        layer_range: [0, 8]
        parameters:
          weight: 1.00
  - sources:
      - model: models/backbones/base
        layer_range: [8, 11]
        parameters:
          weight: 0.00
      - model: models/backbones/mnli
        layer_range: [8, 11]
        parameters:
          density: 0.5
          weight: 1.0

      - model: models/backbones/ag-news
        layer_range: [8, 11]
        parameters:
          density: 0.5
          weight: 1.0

      - model: models/backbones/sst2
        layer_range: [8, 11]
        parameters:
          density: 0.5
          weight: 1.0
  - sources:
      - model: models/backbones/base
        layer_range: [11, 12]
        parameters:
          weight: 1.00

copy_tokenizer: true