merge_method: multislerp
base_model: models/backbones/base
dtype: float32

parameters:
  normalize_weights: true

slices:
  
  - sources:
      - model: models/backbones/sst2
        layer_range: [8, 11]
        parameters:
          weight: 1.0
      
      - model: models/backbones/ag-news
        layer_range: [8, 11]
        parameters:
          weight: 2.3457

      - model: models/backbones/mnli
        layer_range: [8, 11]
        parameters:
          weight: 1.7863

          
copy_tokenizer: true